Docker compose support
boozallen/sdp-libraries pull request #131
Opened 2021-04-21 17:09 UTC by kdendtler

# PR Details

Adding in library support for Docker Compose.

## Description

Added library for Docker Compose that supports up and down commands with multiple files, environment variables, and the ability to pause the pipeline for some amount of time to ensure the containers have had time to deploy before continuing.

## How Has This Been Tested

Tested on local Jenkins deployment using all parameters to deploy containers, execute integration tests against those containers, and tear down when done.
Automated tests written and all existing and new tests pass.

## Types of Changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I am submitting this pull request to the appropriate branch
- [x] I have labeled this pull request appropriately
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

2021-04-22 20:00 UTC, cokieffebah approved these changes

2021-04-22 20:08 UTC, cokieffebah requested changes

2021-04-22 20:08 UTC, cokieffebah commented on libraries/docker_compose/steps/compose.groovy
> +package docker_compose.steps
```suggestion
package libraries.docker_compose.steps
```

2021-04-22 20:08 UTC, cokieffebah commented on libraries/docker_compose/steps/compose.groovy
> +package docker_compose.steps
minor change. will be approved after this

2021-04-22 20:10 UTC, kdendtler commented on libraries/docker_compose/steps/compose.groovy
> +package docker_compose.steps
Done

2021-04-22 20:34 UTC, cokieffebah approved these changes

2021-04-22 20:34 UTC, cokieffebah commented on docs/modules/ROOT/pages/libraries/docker_compose.adoc
> +* Docker installed on Jenkins.
Does this require a docker-compose plugin or that docker-compose is installed on the machine ... or something else?

2021-04-23 11:48 UTC, kdendtler commented on docs/modules/ROOT/pages/libraries/docker_compose.adoc
> +* Docker installed on Jenkins.
Good question, depending on the method used to install docker, docker-compose may come with it but it's worth drawing out the explicit dependency. Updated to include docker-compose as well.

2021-04-23 13:40 UTC, cokieffebah approved these changes

2021-04-23 13:41 UTC, merged

2021-04-23 13:41 UTC, cokieffebah commented
Thanks @kdendtler