WIP:Grype Scanner
boozallen/sdp-libraries pull request #153
Opened 2022-02-16 19:45 UTC by mackeyaj

# PR Details

Added Grype Vulnerability Scanner Step

## Description

Added Grype folder with steps/grype_scan.groovy, resources/transform-grype-scan-results.sh, test/GrypeTestSpec.groovy
Some additional changes to get gradle working

## How Has This Been Tested

The library step has been tested manually in a dev environment using SDP. Unit tests are a work in progress

## Types of Changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I am submitting this pull request to the appropriate branch
- [ ] I have labeled this pull request appropriately
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

2022-02-16 22:13 UTC, steven-terrana requested changes
Overall this is headed in the right direction! Thanks for submitting.

2022-02-16 22:13 UTC, steven-terrana commented on libraries/grype/steps/grype_scan.groovy
> +        docker.image("registry.uip.sh/toolkit/grype:latest").inside() {
From a performance perspective, the way the code is written right now means launching a new instance of the Grype container for every image to be scanned. 

It would be cleaner to do something like: 

```groovy
// save the images to the workspace
List<String> tar_files = []
images.each{ img ->
  String tar = "${img.tag}.tar"
  sh "docker save ${img.registry}/${img.repo}:${img.tag} > ${img.tag}.tar"
  tar_files.push(tar)
}
// scan the images saved
docker.withRegistry...{
  docker.image...{
    tar_files.each{ file ->
      // do the scan
    }
  }
}
```

2022-02-16 22:13 UTC, steven-terrana commented on libraries/grype/steps/grype_scan.groovy
> +        docker.image("registry.uip.sh/toolkit/grype:latest").inside() {
Both of these URLs and the credential ID should be library parameters because they'll change depending on the team using the library.

2022-02-16 22:13 UTC, steven-terrana commented on libraries/grype/steps/grype_scan.groovy
> +          }
There's a couple issues here: 

1. right now, if there were 2 images to scan and the first image had a vulnerability, the second image would never get scanned. You could do this by maintaining a `List<Exception> exceptions = []` and storing the exceptions that occur for each image and then later throwing an exception if that list has any elements. 
2. If there were multiple images, you'd be piping the grype output to the same file for each image. I would recommend basing the name of `RAW_RESULTS_FILE` on the image being scanned so it's unique.

2022-02-16 22:13 UTC, steven-terrana commented on libraries/grype/steps/grype_scan.groovy
> +            writeFile file: TRANSFORMED_RESULSTS_FILE, text: transformed_results.trim()
this is a nit but you could consolidate this to one line by adding a `> ${TRANSFORMED_RESULTS_FILE}` to the end of the `sh` step's script.

2022-02-16 22:13 UTC, steven-terrana commented on libraries/grype/steps/grype_scan.groovy
> +            archiveArtifacts artifacts: "${RAW_RESULTS_FILE}, ${TRANSFORMED_RESULSTS_FILE}"
I'd recommend adding the `allowEmpty` argument to `archiveArtifacts`. 
Users should be able to run this step when no images are being scanned without the step failing.

2022-02-16 22:13 UTC, steven-terrana commented on libraries/grype/README.md
> +|                       |      |               |
Later on, i recommend adding some library parameters. 
You'll want to make sure those are captured and described in this table.

2022-02-16 22:13 UTC, steven-terrana commented on libraries/grype/steps/grype_scan.groovy
> +        docker.image("registry.uip.sh/toolkit/grype:latest").inside() {
We should reuse the `inside_sdp_image` step here. 
If there's a reason we can't, we should fix that reason instead of not using it.

2022-02-16 23:15 UTC, mackeyaj commented on libraries/grype/steps/grype_scan.groovy
> +        docker.image("registry.uip.sh/toolkit/grype:latest").inside() {
My biggest issue was that I could not override the SDP repo to use one with the grype image. The UIP has a Global JTE pipeline config and I was trying to talk them into letting me add the @override annotation to the SDP block so I could incorporate the helper method.

2022-02-17 20:38 UTC, mackeyaj commented on libraries/grype/README.md
> +|   grype_scan()   | Performs the Grype scan against your scaffold build image.             |
would container_vuln_scan or container_vulnerabilty_scan be more descriptive?

2022-02-17 20:48 UTC, mackeyaj commented on libraries/grype/steps/grype_scan.groovy
> +    if (!fileExists("./${GRYPE_CONFIG}")) { error "no grype config found" }
The command will run without the config file, but we want the user to specify a quality gate severity in that config file. If the file does not exist we know there hasnt been a quality_gate set and then fail the build. This could be parameterized but so can everything else you might want to configure via the .grype.yaml file.

2022-02-17 20:56 UTC, mackeyaj commented on libraries/grype/steps/grype_scan.groovy
> +    if (!fileExists("./${GRYPE_CONFIG}")) { error "no grype config found" }
So UIP seems to be doing its own thing. When you build a repo from their scaffold, all the app files seem to be in the container without using the stash/unstash command. I think its part of their build process but I havent found exactly how that is implemented.

2022-02-17 21:01 UTC, mackeyaj commented on libraries/grype/steps/grype_scan.groovy
> +        docker.image("registry.uip.sh/toolkit/grype:latest").inside() {
I had planned to eventually change this to inside_sdp_image. My thought is that the teams using this would just fork the sdp-library repo and add any additional images to that.

2022-02-28 14:34 UTC, mackeyaj commented on libraries/grype/README.md
> +description: Allows you to perform Grype Vulnerabilty scans against your scaffold build image.
Changed to suggested blurb

2022-02-28 14:34 UTC, mackeyaj commented on libraries/grype/README.md
> +This library allows you to scan your scaffold build image.
Changed to suggested blurb.

2022-02-28 14:35 UTC, mackeyaj commented on libraries/grype/README.md
> +|   grype_scan()   | Performs the Grype scan against your scaffold build image.             |
Changed to container_image_scan()

2022-02-28 14:42 UTC, mackeyaj commented on libraries/grype/steps/grype_scan.groovy
> +    def GRYPE_CONFIG = ".grype.yaml"
Added parameterization of grype config using elvis operator.

2022-02-28 14:43 UTC, mackeyaj commented on libraries/grype/steps/grype_scan.groovy
> +    def TRANSFORMED_RESULSTS_FILE = "grype-scan-results.txt"
Specified data types for RAW_RESULTS_FILE and TRANSFORMED_RESULTS_FILE

2022-03-01 19:38 UTC, ConnorDY commented
Commenting just so I can be notified of anything that happens here...

2022-03-03 12:52 UTC, mackeyaj commented on libraries/grype/steps/grype_scan.groovy
> +        docker.image("registry.uip.sh/toolkit/grype:latest").inside() {
added list of tar'ed images

2022-03-03 13:27 UTC, mackeyaj commented on libraries/grype/steps/grype_scan.groovy
> +          }
Attempted fix for this

2022-03-03 13:30 UTC, mackeyaj commented on libraries/grype/steps/grype_scan.groovy
> +            archiveArtifacts artifacts: "${RAW_RESULTS_FILE}, ${TRANSFORMED_RESULSTS_FILE}"
line 54 added allowEmptyArchive: true

2022-06-21 17:48 UTC, ConnorDY reviewed
Code and docs look good! Just need to fix the code formatting in the spec file. 👍

2022-06-21 17:48 UTC, ConnorDY commented on libraries/grype/steps/container_image_scan.groovy
> +                }
Let's drop this `else` block since it's not necessary.

2022-06-27 16:02 UTC, ConnorDY approved these changes

2022-06-29 14:45 UTC, steven-terrana commented
This PR should be merged first: 
https://github.com/mackeyaj/sdp-libraries/pull/1

2022-06-29 15:47 UTC, mackeyaj commented
> This PR should be merged first: [mackeyaj#1](https://github.com/mackeyaj/sdp-libraries/pull/1)

Merge completed!

2022-06-29 16:05 UTC, steven-terrana approved these changes

2022-07-05 15:33 UTC, merged