Dotnet add null safe
boozallen/sdp-libraries pull request #160
Opened 2022-06-02 20:28 UTC by mackeyaj

# PR Details
Adds the null safe operator to config variables and adds a readme file.

## Description
Allows the dotnet library to be imported without specifying resultDir or outDir vars in the pipeline_config. Adds readme file.

## How Has This Been Tested

## Types of Changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I am submitting this pull request to the appropriate branch
- [x] I have labeled this pull request appropriately
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

2022-06-02 20:54 UTC, ConnorDY requested changes
Just a few very minor nitpicks...

2022-06-02 20:54 UTC, ConnorDY commented on libraries/dotnet/README.md
> +# Dotnet
I think we should write this as "DotNet".

2022-06-02 20:54 UTC, ConnorDY commented on libraries/dotnet/README.md
> +This library allows you to perform .Net build and test commands in the sdp dotnet-sdk:5.0 agent container.
".Net" --> ".NET"

"sdp" --> "SDP"

Also, please add backticks (\`) around `dotnet-sdk:5.0` to make this styled a tad better.

2022-06-02 20:54 UTC, ConnorDY commented on libraries/dotnet/README.md
> +| `source_build` | This step leverages the dotnet publish command to build your application and output the results to the specified directory via outDir Variable. outDir defaults to a folder named "b
Please add backticks (\`) around `dotnet publish` and `outDir` to make this styled a tad better. Also please capitalize the "J" in Jenkins.

2022-06-02 20:54 UTC, ConnorDY commented on libraries/dotnet/README.md
> +| `unit_test` | This step leverages the dotnet test command to run the unit, integration and functional tests specified in the application repository and outputs the results to a specified directory
Please add backticks (\`) around `dotnet test` and `resultDir` to make this styled a tad better. Also please capitalize the "J" in Jenkins.

2022-06-02 20:54 UTC, ConnorDY commented on libraries/dotnet/README.md
> +* Access to the dotnet-sdk:5.0 build agent container via the repository defined in your `sdp` library configuration
Please add backticks (\`) around `dotnet-sdk:5.0` to make this styled a tad better. I would remove them from around "sdp" and make SDP all caps.

2022-06-02 20:54 UTC, ConnorDY commented on libraries/dotnet/README.md
> +* The `sdp` library
Please remove the backticks (\`) around "sdp" and make SDP all caps.

2022-06-02 20:54 UTC, ConnorDY commented on libraries/dotnet/README.md
> +description: This library allows you to perform .Net build and test commands in the sdp dotnet-sdk:5.0 agent container
".Net" --> ".NET"

2022-06-02 20:56 UTC, ConnorDY commented
Oh, can you also update the PR title to be a short and well worded description of the PR changes.

For this PR, something like "Added null safe operators and documentation for the .NET library" could work!

2022-06-03 14:58 UTC, psig-bah approved these changes

2022-06-03 15:11 UTC, ConnorDY approved these changes

2022-06-03 22:17 UTC, ConnorDY approved these changes

2022-06-03 22:18 UTC, merged